language: node_js
node_js:
  - "0.12"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma
  - npm install -g bower
  - bower install

script: 
  - grunt continuous

after_success:
  - perl create_tag.pl 
